### ISSUE TITLE
Lidarr

### ISSUE THREAD

**Issue by woble** [binhex/arch-radarr#1]
Didn't know where to reach you so posting it here, hope it's ok. Any chance you can create a Lidarr docker?

https://github.com/lidarr/Lidarr

**Comment by binhex** [comment]
i will take a look at it when i get some time, thanks for the link.

**Comment by woble** [comment]
Thanks! If possible, could you perhaps also look into [NZBHydra](https://github.com/theotherp/nzbhydra). There's already one from linuxserver, but your dockers have a much slimmer and streamlined setup.
