### ISSUE TITLE
IMDB list will not connect

### ISSUE THREAD

**Issue by CanonCan** [binhex/arch-radarr#2]
I have two watch lists that when first set up worked...now only one works
First working user is ls023263032
Broken one is ur33918291

if i use test i get this
Unable to connect to list, check the log for more details

the logs as it tells 

  | Component | Message | Time
-- | -- | -- | --
  | NzbDroneErrorPipeline | Invalid request Validation failed: -- Unable to connect to list, check the log for more details | 12:06am
  | RadarrLists | Unable to connect to list: Error while calling api: Internal Server Error Full error(s): Internal Server Error (500, RayId: d00db131-d42c-4117-b38d-0dc8a5e91ded), Details: An error has occurred and this resource cannot be displayed.

**Comment by binhex** [comment]
your best bet is to post this on the github radarr repo as an issue giving as much detail as possible, keep in mind i only package radarr, i am not a radarr developer.

**Comment by CanonCan** [comment]
Thanks Binhex I will sorry to bother you i does seem to be an API Issue with AWS so yeah. Pretty sure it’s. Backend problem

____________________
Michael
