### ISSUE TITLE
Old version of mono in radarr/sonarr containers

### ISSUE THREAD

**Issue by fryfrog** [binhex/arch-radarr#3]
The version inside the latest container for both radarr and sonarr is 5.10, but the latest on Arch is 5.14. It doesn't look like you're hard coding version, so maybe a new build just needs to be done?

**Comment by fryfrog** [comment]
Also, 09ffa38bf4279ea2886ad714f967400be8138983 isn't needed anymore. It has long since been included in Sonarr and Radarr.

**Comment by fryfrog** [comment]
Hey @binhex, looks like you did update it at some point because right now it has 5.12... but current in Arch is 5.16 and 5.18 is in testing and presumably comes out soon.

I know you've had real life becoming a priority, how would you feel about teaching me basic maintenance of your Docker system so I could help keep it up to date?

**Comment by fryfrog** [comment]
Or is there maybe a way you could split out mono into an `arch-mono` docker that auto-updates and then let your few mono packages like jackett, sonarr, radarr and lidarr automatically rebuild when that one does?

**Comment by binhex** [comment]
the out of date mono version is not due to time constraints, its actually by design, so let me explain...

as you know arch linux is a rolling release, this has challenges when you use it as a base os for docker, the main challenge being that packages are continually being updated, because of this if you update the image every time you build then the caching of layers reduces every time you rebuild, as the layers within the image become unique and thus do not share between other images, if you rebuild for long enough then pretty much every layer is unique and thus you have to pull down the entire image every time, which will increase disk usage and time spent downloading the image (no layers cached means a FULL pull down of the image).

so to get around this i make use of the arch archive repo, i edit the pacman config file to point at a set point in time, thus any additional packages installed via pacman use the same point in time and thus the caching of layers is maintained. 

this isnt perfect and sometimes i do need to ref the live repo, as dependancies change and sometimes an app requires a later version of a package.

so it is currently not possible to be completely up to date and also make use of caching without the use of point in time builds.

got a question for you, why the urgency to update mono?, are you aware of some issues with the current version?.

**Comment by fryfrog** [comment]
I'm not looking for your mono based images to be rolling release based, I get it. But you clearly have bases with Mono `5.16`, `5.14` and `5.10`. It would be great if all the Mono based dockers used the same, probably most recent version. It makes sense to pin the Mono version (by pinning the whole stack) if there are known issues, but not if there aren't.

It also means the rest of the container is as out of date as the Mono version. And Sonarr/Radarr are very similar, so supporting your containers when they're that different can be a little frustrating. The only reasonable way to confirm it isn't the Mono / libmediainfo / etc is to ask them to run another more up to date image like LSIO. And once they've done that, why bother going back?

I'm not aware of any issues with 5.10, 5.14 or 5.16. There is no urgency here, as you can see the issue is old as heck. It just surprises me every time someone shows up w/ a binhex container and the mono is *months* out of date. I'm not sure if you're aware, but Arch is a rolling distro ;)

Help me help you! :)

**Comment by binhex** [comment]
ok cool :-), i get that support gets tricky when things are different, thus my attempt to keep things sameish by using a point in time for arch repo and using a common base, im honestly not trying to be difficult!.

what you are seeing is version creep over time, as the base updates so does the point in time at which the image is looking at, thus if radarr builds in say sept 2018 then the mono version at that time maybe 5.12, if sonarr is updated more frequently then the chances are it will pick up a newer base image and thus the version of mono maybe 5.14 or later.  

i have two options here:-

1. always use the same base and never update (not really an option as newer apps may required packages that dont exist on older snapshots of arch repo).

2.always update all mono based images at the same time so they all update to the same level of mono, again not really ideal, as it means needless building and pulling down (people automate pulls via watchtower) of multiple images by users.

the third option you suggested of creating a common mono image would allow all mono based apps to have the same version of mono, but again would be a stuck point in time with mono, until i rebuilt this image and then of course rebuilt all the images, causing mass downloads by users.

as we both agree, arch linux is a rolling distro :-), and therefore we need to roll with the updates, this includes mono, i have coped with this as best i can by only updating mono when the image requires rebuilding (aka the app has a new release), this reduces builds and reduces pulls from the user, BUT as you so rightly put it, it does mean potentially different versions of mono to support as the base image updates (update base every 2 months). i can lengthen the time between base updates, this will increase the chances of the same version of mono being used, but with the side effect that updates to mono will be less frequent, what do you think?.

**Comment by binhex** [comment]
i think in short my question to you is how do i create docker images with the same version of mono when using a rolling release distro WITHOUT the need to rebuild every mono based app from scratch every time and thus result in massive docker images with zero caching?, if you can give me a solution to this quandary then i will be very happy indeed :-).

**Comment by fryfrog** [comment]
I think a compromise between the two is pretty reasonable. If they *all* use the same base image, they all get the benefit of caching right? And Mono doesn't actually get updated *that* frequently. It doesn't seem like an update every 2-8 weeks is a big deal. I know Sonarr and Radarr don't do major updates very often, so tying the base updates to them is how they get behind, right?

But the Jackett team releases updates *constantly*, how is that one behind? Or am I still missing something?

**Comment by binhex** [comment]
> I think a compromise between the two is pretty reasonable. If they _all_ use the same base image, they all get the benefit of caching right?

this is true , obviously if that base image does change then in order for all to use the same version of mono they will need to be rebuilt, but i agree that is reasonable.

> I know Sonarr and Radarr don't do major updates very often, so tying the base updates to them is how they get behind, right?

thats exactly it, you got it.

> But the Jackett team releases updates _constantly_, how is that one behind? Or am I still missing something?

you are missing something, jackett has a very nasty memory leak, which is particularly nasty with the later versions of mono, thus this particular docker image is (currently) tied to 'mono~5.14.0.177' and this has stabilised it.

i appreciate the feedback, nice to bounce ideas of somebody, i think i will take your idea forward and look into creating a common mono base image (excluding jackett)

**Comment by fryfrog** [comment]
I appreciate how open to feedback you are for your images, you're one of my favorites to work with. :)

**Comment by binhex** [comment]
fyi @fryfrog image now created 'arch-int-mono' and radarr, lidarr, and sonarr re-created, so all 3 should now be using the latest version of mono.

**Comment by fryfrog** [comment]
Great success!
