### ISSUE TITLE
What is the Data dir for?

### ISSUE THREAD

**Issue by Ryonez** [binhex/arch-radarr#6]
Hi, I'm setting this up for the first time, and am struggling to sort out how the folders are meant to be mapped.

Is the data dir meant to be mapped to the nzbget download folder?

If someone could provide a basic map of how they do it I'd be really grateful.

**Comment by SultanSGillani** [comment]
Asking the same question here

**Comment by Ryonez** [comment]
I've sorted it out since then, some time ago.
No, you don't need to link those to folders together, but data folder is where the downloaded data goes. if you use sonarr/radarr/etc, make sure they can access them and configure them to look at the folder to pick up the downloads.
